services:
  generator:
    build:
      context: ../neo4j-gener/.
      dockerfile: Containerfile
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M
    environment:
      - NEO4J_DSN=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=neo4j_pass
    develop:
      watch:
        # rebuild image and recreate service
        - path: .
          action: rebuild
