services:
  neo4j:
    image: neo4j:2025.06.0-enterprise
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
    # TODO: use backup for load testing
    # volumes:
    #   - "./backups:/backups"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/neo4j_pass
      NEO4J_PLUGINS: '["apoc"]'
      # NEO4J_apoc_import_file_enabled: "true"
      # NEO4J_apoc_export_file_enabled: "true"

  nats:
    image: nats:2.8.4-alpine
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.25"
          memory: 20M
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js -m 8222

  cdc:
    build:
      context: .
      dockerfile: Containerfile
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M
    environment:
      - NEO4J_DSN=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=neo4j_pass
      - NATS_DSN=nats://nats:4222
      - SLOG_LEVEL=DEBUG
    develop:
      watch:
        # rebuild image and recreate service
        - path: .
          action: rebuild
